package engine:api@0.1.0;

interface engine-types {
    variant value {
        none,
        str(string),
        int64(s64),
        uint64(u64),
        float64(f64),
        boolean(bool),
        any(list<u8>),
    }

    record kvpair {
        key: string,
        value: value,
    }

    type run-id = u64;

    type unixtime = u64;

    record workflow-run {
        id: run-id,
        input: list<kvpair>,
        timestamp: unixtime,
    }

    enum code {
        not-found,
        empty-input,
    }

    record workflow-error {
        err: string,
        code: code,
    }

    record history {
        tasks-result: list<kvpair>
    }

    record signal {
        payload: list<kvpair>
    }

    record workflow-info {
        name: string,
        version: string,
        description: string,
    }
}